improve r-o-m delay and exit warning only if verbose

diff --git a/r-o-m b/r-o-m
--- a/r-o-m
+++ b/r-o-m
@@ -260,8 +260,10 @@ for try in $(seq 1 "$REPEAT"); do
 	if [[ -z $NOOP ]]; then
 	    "$ROGOMATIC"
 	    status="$?"
-	    if [[ $status -ne 0 ]]; then
-		echo "$0: Warning: $ROGOMATIC failed, error: $status" 1>&2
+	    if [[ $V_FLAG -ge 1 ]]; then
+		if [[ $status -ne 0 ]]; then
+		    echo "$0: Warning: $ROGOMATIC failed, error: $status" 1>&2
+		fi
 	    fi
 	elif [[ $V_FLAG -ge 5 ]]; then
 	    echo "$0: debug[5]: because of -n, did not execute: $ROGOMATIC" 1>&2
@@ -274,8 +276,10 @@ for try in $(seq 1 "$REPEAT"); do
 	if [[ -z $NOOP ]]; then
 	    "$ROGOMATIC" -e
 	    status="$?"
-	    if [[ $status -ne 0 ]]; then
-		echo "$0: Warning: $ROGOMATIC -e failed, error: $status" 1>&2
+	    if [[ $V_FLAG -ge 1 ]]; then
+		if [[ $status -ne 0 ]]; then
+		    echo "$0: Warning: $ROGOMATIC -e failed, error: $status" 1>&2
+		fi
 	    fi
 	elif [[ $V_FLAG -ge 5 ]]; then
 	    echo "$0: debug[5]: because of -n, did not execute: $ROGOMATIC -e" 1>&2
@@ -287,7 +291,7 @@ for try in $(seq 1 "$REPEAT"); do
     if [[ $V_FLAG -ge 1 ]]; then
         echo "$0: debug[1]: about to run: reset" 1>&2
     fi
-    sleep 2
+    sleep 4
     if [[ -z $NOOP ]]; then
 	reset
 	status="$?"
